### ISSUE TITLE
Optimizing Performance

### ISSUE THREAD

**Issue by zkagin** [kipp-bayarea/google_classroom#17]
Right now all calls to the Google Classroom API are done sequentially and individually. As we identify bottlenecks, the goal is to optimize these calls and minimize the time to run this from hours to minutes. This can potentially be done through both batch calling the endpoints and through parallelization of calls.

Further details are pending a performance test.

**Comment by dchess** [comment]
@zkagin Are you thinking of using threading to address this or async?

**Comment by zkagin** [comment]
My plan was to try the Google batching API first and see how much progress we make, and then if we need to optimize more, use async. Async is generally better for tasks with delays, whereas threading would be more useful if we had a lot of local processing to be done. If it turns out our bottleneck is in processing the incoming data, we can definitely look at using threading as well or instead.
