### ISSUE TITLE
Adding Notifications

### ISSUE THREAD

**Issue by dchess** [kipp-bayarea/google_classroom#19]
The current job would benefit from a way to notify success/errors when running as a job. We do this standard by adding a mailer that emails a Slack channel, but am wondering if we need a broader approach for this project.

**Comment by dchess** [comment]
@zkagin I'm going to add our standard Mailer for now and we can refactor/improve later.

**Comment by zkagin** [comment]
Sounds great, happy to take a look once you've implemented it.
