### ISSUE TITLE
Fix request retries to be per request

### ISSUE THREAD

**Issue by dchess** [kipp-bayarea/google_classroom#37]
Currently with the new method `get_and_write_to_db` when a request fails, the entire loop starts again. This should happen per request so that if a single request fails only that request retries. 

I.E. if the students query loops over 1200 courses and a single course request fails midway it starts back over at course 1. It should just retry that single course request and continue on.

**Comment by zkagin** [comment]
Yep, should be straightforward to factor out that piece and add retry logic to it.

How frequently are you getting failures? Is there any cause in particular that is failing?

**Comment by dchess** [comment]
@zkagin I spotted it while troubleshooting the student submission endpoint, but would most likely occur with API timeouts when requests are coming too fast or when there is a malformed request or unavailable data.
