### ISSUE TITLE
Batch request ID already exists

### ISSUE THREAD

**Issue by dchess** [kipp-bayarea/google_classroom#59]
> Traceback (most recent call last):
>   File "main.py", line 131, in <module>
>     main(Config)
>   File "main.py", line 126, in main
>     StudentSubmissions(classroom_service, sql, config).batch_pull_data(course_ids)
>   File "/code/timer.py", line 22, in wrapper
>     results = func(*args, **kwargs)
>   File "/code/api.py", line 182, in batch_pull_data
>     batch.add(request, request_id=request_id)
>   File "/root/.local/share/virtualenvs/code-_Py8Si6I/lib/python3.7/site-packages/googleapiclient/_helpers.py", line 134, in positional_wrapper
>     return wrapped(*args, **kwargs)
>   File "/root/.local/share/virtualenvs/code-_Py8Si6I/lib/python3.7/site-packages/googleapiclient/http.py", line 1398, in add
>     raise KeyError("A request with this ID already exists: %s" % request_id)
> KeyError: 'A request with this ID already exists: 41010390897;None;2'

**Comment by dchess** [comment]
@zkagin I encountered this a couple times while running the CourseWork and StudentSubmissions queries. It seems related to the retry logic adding a new batch request when the ID already exists. I'm not 100% sure its from the retry, but that's where my brain went when I saw it. So far I've been able to work around it by restarting the job.

**Comment by zkagin** [comment]
@dchess I am not able to repro this even while running everything together. I don't see any mechanism by which a the remaining_requests can have duplicate keys. There are a few ways to solve it (use a set or key-dictionary instead), but I'm afraid that may cover up some deeper or unexplained issue.

I am curious if the long execution time of the callback may be causing some weird race condition, so my first step is going to be moving the db write out of that, and then we can see if you are still running into this error.

**Comment by dchess** [comment]
@zkagin I didn't encounter this today when running the job end-to-end so I'm wondering if this was related to simultaneous runs using the same service account. I agree about pivoting to the database writes issue and we can monitor if this continues to occur.

**Comment by zkagin** [comment]
@dchess That could very well be. Let's leave this open for a few days, and if (especially after the latest PR to improve performance) you're not running into it then, we can close this out.

**Comment by dchess** [comment]
Closing since this hasn't been seen in tests or production for the last month.
