### ISSUE TITLE
Usage Data fail on first run

### ISSUE THREAD

**Issue by denglender** [kipp-bayarea/google_classroom#68]
@dchess - Was thinking more about the error we looked at today, and (admittedly not having fully immersed myself in the code), I don't think it was due to not having quotes around the date in the .env file.

I think it will always fail if there is no data in the student usage table and that it only worked today because my workaround fed data into the student usage data prior uncommenting the original code.

```
        usage = StudentUsage(admin_reports_service, sql, config, org_unit_id)
        last_date = usage.get_last_date()
        start_date = last_date + timedelta(days=1) or datetime.strptime(config.SCHOOL_YEAR_START, "%Y-%m-%d")
```

My quick read of StudentUsage.get_last_date() is that it's going to return None if there's no data previously loaded in the table, at which point the next line will throw an error because you can't add to None.  

I had enough energy to type up this issue, but not enough to clear my database and try from scratch again to double check, so hopefully this is useful, and apologies if it's a false alarm.

**Comment by zkagin** [comment]
@denglender I just confirmed the error I assume you're receiving (`TypeError: unsupported operand type(s) for +: 'NoneType' and 'datetime.timedelta'`), and will have a fix out shortly.

**Comment by denglender** [comment]
Correct!
________________________________

**Comment by zkagin** [comment]
PR submitted, @dchess to review / merge when ready.

**Comment by dchess** [comment]
@denglender I've merged this fix. You can pull the latest changes to your local now.
