### ISSUE TITLE
Add individualStudentOptions for courseWork

### ISSUE THREAD

**Issue by dchess** [kipp-bayarea/google_classroom#82]
There is a [nested dataset within the courseWor](https://developers.google.com/classroom/reference/rest/v1/IndividualStudentsOptions)k endpoint that is used when an assignment is assigned to a subset of students. This is necessary to pull in so that it can be determined which assignments were not assigned to all students and so missing assignments in analysis can be more exact. However, adding this directly in the CourseWork table would blow up the data and it would no longer be at the same level of granularity. 

I propose we add a new table that maps the courseWorkId to the studentId from this individualStudentOptions list.

**Comment by dchess** [comment]
@zkagin I'm not sure this is necessary. Based on some analysis, this should be possible to infer by checking records and state in the studentSubmissions table. If an assignment was assigned to a student but hadn't been turned in it would have the NEW or CREATED state. However, if it was not assigned at all there would be no record at all.

**Comment by zkagin** [comment]
Makes sense. Is it something you think would still be useful, or should we hold off on it for now?

**Comment by dchess** [comment]
@zkagin I think we can close this for now.
