### ISSUE TITLE
Aliases endpoint does not record courseId

### ISSUE THREAD

**Issue by richmcd** [kipp-bayarea/google_classroom#92]
The course.aliases.list API responds with an array of CourseAlias objects.  CourseAlias does not contain a courseId property though.  Unfortunately, to be useful from a data reporting perspective, we need the courseId in the CourseAliases table.

I've been able to work around this issue for now by specifically handling aliases in the internal callback method of api.py -> EndPoint.batch_pull_data.  If you insert the following lines starting at line 220 of api.py (right after the nextPageToken conditional block) it will add the courseId property to each CourseAlias object in the response["aliases"] array.

```
            """Fix up alias records to include course Id"""
            if "aliases" in response:
                for alias in response["aliases"]:
                    if "courseId" not in alias:
                        alias["courseId"] = course_id

```

I don't think this should be the permanent fix, as it breaks inheritance (the parent shouldn't know about things that don't apply to all children), but the only other way I could see for now was to reimplement the batch_pull_data callback as a class method on EndPoint that could be overridden in CourseAliases with the updated callback code.  That looked like a lot more work though and would require refactoring external references like batch_data.  I'm sure there's a better way to do this as well, given I'm not much of a python coder yet.

**Comment by dchess** [comment]
@richmcd Thanks for flagging this. We are working on some changes to the codebase right now and will take this into account. We appreciate the contribution! Please let us know if you find any other bugs or issues.

**Comment by zkagin** [comment]
@richmcd Thanks for pointing this out. I submitted a fix that takes a similar approach but applies it more generally. It may need to wait for merging until a dependent PR is also merged.

**Comment by richmcd** [comment]
Thanks @zkagin, I'll keep an eye out for it.
