### ISSUE TITLE
Add additional course statuses to Courses Endpoint

### ISSUE THREAD

**Issue by dchess** [kipp-bayarea/google_classroom#95]
@zkagin When a course is archived in Google Classroom it doesn't get pulled by the API. This currently only pulls active.

**Comment by dchess** [comment]
I think this can be fixed with a simple change to the status list in:
https://github.com/kipp-bayarea/google_classroom/blob/2310e846093415cddda96987558409298d4df056/google_classroom/api.py#L407-L412

**Comment by dchess** [comment]
It will also likely require a change to the course id pull to filter on active status though:
https://github.com/kipp-bayarea/google_classroom/blob/2310e846093415cddda96987558409298d4df056/google_classroom/main.py#L115

**Comment by zkagin** [comment]
Just to clarify, do you want to pull in inactive courses to the database as well then?
